export { default as Blog } from './Blog/Blog'
export { default as Portfolio } from './Portfolio/Portfolio'
export { default as Gallery } from './Gallery/Gallery'
export { default as About } from './About/About'
export { default as Admin } from './Admin/Admin'